### PR TITLE
Added ReadWriteMultipleRegisters function

### PR DESCRIPTION
**Pull request by mrksngl**
Added function 23 (Read/Write Multiple Registers):
 * merely a copy with little changes of `WriteMultipleRegistersRequest` for the request
 * and of `ReadHoldingRegistersResponse` for the response
 * plus corresponding changes in the coders

### CODE REVIEW

**Comment by kevinherron** [comment]
Is there a checkbox in your view of this PR to allow me to push changes to this branch?

**Comment by mrksngl** [comment]
I'm not very used to github, but I don't see any such checkbox.
You can of course also just take the commit from my forked repository and do whatever you like with it.

**Comment by mrksngl** [comment]
Oh I just found "convert to draft", would that be what you need?

**Comment by kevinherron** [comment]
No, there's some checkbox that gives me permission to push commits to this branch. I thought it was enabled by default.

You can just apply this patch instead. I just fixed some of the formatting and imports according to the unofficial code style I'm using here. My fault for not setting up checkstyle to formally define one.

```
Index: modbus-codec/src/main/java/com/digitalpetri/modbus/codec/ModbusRequestDecoder.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- modbus-codec/src/main/java/com/digitalpetri/modbus/codec/ModbusRequestDecoder.java	(revision 283f0c19e40e8314d370bf0f0c1368942f18c89f)
+++ modbus-codec/src/main/java/com/digitalpetri/modbus/codec/ModbusRequestDecoder.java	(revision adc316d7abecae82e5dce4fdd35e200cede23f44)
@@ -19,7 +19,16 @@
 import com.digitalpetri.modbus.FunctionCode;
 import com.digitalpetri.modbus.ModbusPdu;
 import com.digitalpetri.modbus.UnsupportedPdu;
-import com.digitalpetri.modbus.requests.*;
+import com.digitalpetri.modbus.requests.MaskWriteRegisterRequest;
+import com.digitalpetri.modbus.requests.ReadCoilsRequest;
+import com.digitalpetri.modbus.requests.ReadDiscreteInputsRequest;
+import com.digitalpetri.modbus.requests.ReadHoldingRegistersRequest;
+import com.digitalpetri.modbus.requests.ReadInputRegistersRequest;
+import com.digitalpetri.modbus.requests.ReadWriteMultipleRegistersRequest;
+import com.digitalpetri.modbus.requests.WriteMultipleCoilsRequest;
+import com.digitalpetri.modbus.requests.WriteMultipleRegistersRequest;
+import com.digitalpetri.modbus.requests.WriteSingleCoilRequest;
+import com.digitalpetri.modbus.requests.WriteSingleRegisterRequest;
 import io.netty.buffer.ByteBuf;
 import io.netty.handler.codec.DecoderException;
 
@@ -30,8 +39,8 @@
         int code = buffer.readByte();
 
         FunctionCode functionCode = FunctionCode
-                .fromCode(code)
-                .orElseThrow(() -> new DecoderException("invalid function code: " + code));
+            .fromCode(code)
+            .orElseThrow(() -> new DecoderException("invalid function code: " + code));
 
         return decodeResponse(functionCode, buffer);
     }
Index: modbus-codec/src/main/java/com/digitalpetri/modbus/codec/ModbusRequestEncoder.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- modbus-codec/src/main/java/com/digitalpetri/modbus/codec/ModbusRequestEncoder.java	(revision 283f0c19e40e8314d370bf0f0c1368942f18c89f)
+++ modbus-codec/src/main/java/com/digitalpetri/modbus/codec/ModbusRequestEncoder.java	(revision adc316d7abecae82e5dce4fdd35e200cede23f44)
@@ -17,7 +17,16 @@
 package com.digitalpetri.modbus.codec;
 
 import com.digitalpetri.modbus.ModbusPdu;
-import com.digitalpetri.modbus.requests.*;
+import com.digitalpetri.modbus.requests.MaskWriteRegisterRequest;
+import com.digitalpetri.modbus.requests.ReadCoilsRequest;
+import com.digitalpetri.modbus.requests.ReadDiscreteInputsRequest;
+import com.digitalpetri.modbus.requests.ReadHoldingRegistersRequest;
+import com.digitalpetri.modbus.requests.ReadInputRegistersRequest;
+import com.digitalpetri.modbus.requests.ReadWriteMultipleRegistersRequest;
+import com.digitalpetri.modbus.requests.WriteMultipleCoilsRequest;
+import com.digitalpetri.modbus.requests.WriteMultipleRegistersRequest;
+import com.digitalpetri.modbus.requests.WriteSingleCoilRequest;
+import com.digitalpetri.modbus.requests.WriteSingleRegisterRequest;
 import io.netty.buffer.ByteBuf;
 import io.netty.handler.codec.EncoderException;
 import io.netty.util.ReferenceCountUtil;
Index: modbus-codec/src/main/java/com/digitalpetri/modbus/codec/ModbusResponseDecoder.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- modbus-codec/src/main/java/com/digitalpetri/modbus/codec/ModbusResponseDecoder.java	(revision 283f0c19e40e8314d370bf0f0c1368942f18c89f)
+++ modbus-codec/src/main/java/com/digitalpetri/modbus/codec/ModbusResponseDecoder.java	(revision adc316d7abecae82e5dce4fdd35e200cede23f44)
@@ -20,7 +20,17 @@
 import com.digitalpetri.modbus.FunctionCode;
 import com.digitalpetri.modbus.ModbusPdu;
 import com.digitalpetri.modbus.UnsupportedPdu;
-import com.digitalpetri.modbus.responses.*;
+import com.digitalpetri.modbus.responses.ExceptionResponse;
+import com.digitalpetri.modbus.responses.MaskWriteRegisterResponse;
+import com.digitalpetri.modbus.responses.ReadCoilsResponse;
+import com.digitalpetri.modbus.responses.ReadDiscreteInputsResponse;
+import com.digitalpetri.modbus.responses.ReadHoldingRegistersResponse;
+import com.digitalpetri.modbus.responses.ReadInputRegistersResponse;
+import com.digitalpetri.modbus.responses.ReadWriteMultipleRegistersResponse;
+import com.digitalpetri.modbus.responses.WriteMultipleCoilsResponse;
+import com.digitalpetri.modbus.responses.WriteMultipleRegistersResponse;
+import com.digitalpetri.modbus.responses.WriteSingleCoilResponse;
+import com.digitalpetri.modbus.responses.WriteSingleRegisterResponse;
 import io.netty.buffer.ByteBuf;
 import io.netty.handler.codec.DecoderException;
 
Index: modbus-codec/src/main/java/com/digitalpetri/modbus/codec/ModbusResponseEncoder.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- modbus-codec/src/main/java/com/digitalpetri/modbus/codec/ModbusResponseEncoder.java	(revision 283f0c19e40e8314d370bf0f0c1368942f18c89f)
+++ modbus-codec/src/main/java/com/digitalpetri/modbus/codec/ModbusResponseEncoder.java	(revision adc316d7abecae82e5dce4fdd35e200cede23f44)
@@ -17,7 +17,17 @@
 package com.digitalpetri.modbus.codec;
 
 import com.digitalpetri.modbus.ModbusPdu;
-import com.digitalpetri.modbus.responses.*;
+import com.digitalpetri.modbus.responses.ExceptionResponse;
+import com.digitalpetri.modbus.responses.MaskWriteRegisterResponse;
+import com.digitalpetri.modbus.responses.ReadCoilsResponse;
+import com.digitalpetri.modbus.responses.ReadDiscreteInputsResponse;
+import com.digitalpetri.modbus.responses.ReadHoldingRegistersResponse;
+import com.digitalpetri.modbus.responses.ReadInputRegistersResponse;
+import com.digitalpetri.modbus.responses.ReadWriteMultipleRegistersResponse;
+import com.digitalpetri.modbus.responses.WriteMultipleCoilsResponse;
+import com.digitalpetri.modbus.responses.WriteMultipleRegistersResponse;
+import com.digitalpetri.modbus.responses.WriteSingleCoilResponse;
+import com.digitalpetri.modbus.responses.WriteSingleRegisterResponse;
 import io.netty.buffer.ByteBuf;
 import io.netty.handler.codec.EncoderException;
 import io.netty.util.ReferenceCountUtil;
Index: modbus-core/src/main/java/com/digitalpetri/modbus/requests/ReadWriteMultipleRegistersRequest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- modbus-core/src/main/java/com/digitalpetri/modbus/requests/ReadWriteMultipleRegistersRequest.java	(revision 283f0c19e40e8314d370bf0f0c1368942f18c89f)
+++ modbus-core/src/main/java/com/digitalpetri/modbus/requests/ReadWriteMultipleRegistersRequest.java	(revision adc316d7abecae82e5dce4fdd35e200cede23f44)
@@ -17,12 +17,12 @@
 
 package com.digitalpetri.modbus.requests;
 
+import java.nio.ByteBuffer;
+
 import com.digitalpetri.modbus.FunctionCode;
 import io.netty.buffer.ByteBuf;
 import io.netty.buffer.Unpooled;
 
-import java.nio.ByteBuffer;
-
 /**
  * This function code is used to write a block of contiguous registers (1 to 123 registers) in a remote device.
  * <p>
@@ -30,62 +30,62 @@
  */
 public class ReadWriteMultipleRegistersRequest extends ByteBufModbusRequest {
 
-	private final int readAddress;
-	private final int readQuantity;
-	private final int writeAddress;
-	private final int writeQuantity;
+    private final int readAddress;
+    private final int readQuantity;
+    private final int writeAddress;
+    private final int writeQuantity;
 
-	/**
-	 * @param readAddress  0x0000 to 0xFFFF (0 to 65535)
-	 * @param readQuantity 0x0001 to 0x007B (1 to 123)
+    /**
+     * @param readAddress   0x0000 to 0xFFFF (0 to 65535)
+     * @param readQuantity  0x0001 to 0x007B (1 to 123)
      * @param writeAddress  0x0000 to 0xFFFF (0 to 65535)
      * @param writeQuantity 0x0001 to 0x007B (1 to 123)
-	 * @param values       buffer of at least N bytes, where N = quantity * 2
-	 */
-	public ReadWriteMultipleRegistersRequest(int readAddress, int readQuantity, int writeAddress, int writeQuantity,
-											 byte[] values) {
-		this(readAddress, readQuantity, writeAddress, writeQuantity, Unpooled.wrappedBuffer(values));
-	}
+     * @param values        buffer of at least N bytes, where N = quantity * 2
+     */
+    public ReadWriteMultipleRegistersRequest(int readAddress, int readQuantity, int writeAddress, int writeQuantity,
+                                             byte[] values) {
+        this(readAddress, readQuantity, writeAddress, writeQuantity, Unpooled.wrappedBuffer(values));
+    }
 
-	/**
-	 * @param readAddress  0x0000 to 0xFFFF (0 to 65535)
-	 * @param readQuantity 0x0001 to 0x007B (1 to 123)
+    /**
+     * @param readAddress   0x0000 to 0xFFFF (0 to 65535)
+     * @param readQuantity  0x0001 to 0x007B (1 to 123)
      * @param writeAddress  0x0000 to 0xFFFF (0 to 65535)
      * @param writeQuantity 0x0001 to 0x007B (1 to 123)
-	 * @param values       buffer of at least N bytes, where N = quantity * 2
-	 */
-	public ReadWriteMultipleRegistersRequest(int readAddress, int readQuantity, int writeAddress, int writeQuantity,
-											 ByteBuffer values) {
-		this(readAddress, readQuantity, writeAddress, writeQuantity, Unpooled.wrappedBuffer(values));
-	}
+     * @param values        buffer of at least N bytes, where N = quantity * 2
+     */
+    public ReadWriteMultipleRegistersRequest(int readAddress, int readQuantity, int writeAddress, int writeQuantity,
+                                             ByteBuffer values) {
+        this(readAddress, readQuantity, writeAddress, writeQuantity, Unpooled.wrappedBuffer(values));
+    }
 
-	/**
-	 * Create a request using a {@link ByteBuf}. The buffer will have its reference count decremented after encoding.
-	 *
-	 * @param readAddress   0x0000 to 0xFFFF (0 to 65535)
-	 * @param readQuantity  0x0001 to 0x007B (1 to 123)
-	 * @param writeAddress  0x0000 to 0xFFFF (0 to 65535)
-	 * @param writeQuantity 0x0001 to 0x007B (1 to 123)
-	 * @param values        buffer of at least N bytes, where N = quantity * 2
-	 */
-	public ReadWriteMultipleRegistersRequest(int readAddress, int readQuantity, int writeAddress, int writeQuantity,
-											 ByteBuf values) {
-		super(values, FunctionCode.ReadWriteMultipleRegisters);
+    /**
+     * Create a request using a {@link ByteBuf}. The buffer will have its reference count decremented after encoding.
+     *
+     * @param readAddress   0x0000 to 0xFFFF (0 to 65535)
+     * @param readQuantity  0x0001 to 0x007B (1 to 123)
+     * @param writeAddress  0x0000 to 0xFFFF (0 to 65535)
+     * @param writeQuantity 0x0001 to 0x007B (1 to 123)
+     * @param values        buffer of at least N bytes, where N = quantity * 2
+     */
+    public ReadWriteMultipleRegistersRequest(int readAddress, int readQuantity, int writeAddress, int writeQuantity,
+                                             ByteBuf values) {
+        super(values, FunctionCode.ReadWriteMultipleRegisters);
 
-		this.readAddress = readAddress;
-		this.readQuantity = readQuantity;
+        this.readAddress = readAddress;
+        this.readQuantity = readQuantity;
 
-		this.writeAddress = writeAddress;
-		this.writeQuantity = writeQuantity;
-	}
+        this.writeAddress = writeAddress;
+        this.writeQuantity = writeQuantity;
+    }
 
-	public int getReadAddress() {
-		return readAddress;
-	}
+    public int getReadAddress() {
+        return readAddress;
+    }
 
-	public int getReadQuantity() {
-		return readQuantity;
-	}
+    public int getReadQuantity() {
+        return readQuantity;
+    }
 
     public int getWriteAddress() {
         return writeAddress;
@@ -95,8 +95,8 @@
         return writeQuantity;
     }
 
-	public ByteBuf getValues() {
-		return super.content();
-	}
+    public ByteBuf getValues() {
+        return super.content();
+    }
 
 }
Index: modbus-slave-tcp/src/main/java/com/digitalpetri/modbus/slave/ServiceRequestHandler.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- modbus-slave-tcp/src/main/java/com/digitalpetri/modbus/slave/ServiceRequestHandler.java	(revision 283f0c19e40e8314d370bf0f0c1368942f18c89f)
+++ modbus-slave-tcp/src/main/java/com/digitalpetri/modbus/slave/ServiceRequestHandler.java	(revision adc316d7abecae82e5dce4fdd35e200cede23f44)
@@ -17,8 +17,28 @@
 package com.digitalpetri.modbus.slave;
 
 import com.digitalpetri.modbus.ExceptionCode;
-import com.digitalpetri.modbus.requests.*;
-import com.digitalpetri.modbus.responses.*;
+import com.digitalpetri.modbus.requests.MaskWriteRegisterRequest;
+import com.digitalpetri.modbus.requests.ModbusRequest;
+import com.digitalpetri.modbus.requests.ReadCoilsRequest;
+import com.digitalpetri.modbus.requests.ReadDiscreteInputsRequest;
+import com.digitalpetri.modbus.requests.ReadHoldingRegistersRequest;
+import com.digitalpetri.modbus.requests.ReadInputRegistersRequest;
+import com.digitalpetri.modbus.requests.ReadWriteMultipleRegistersRequest;
+import com.digitalpetri.modbus.requests.WriteMultipleCoilsRequest;
+import com.digitalpetri.modbus.requests.WriteMultipleRegistersRequest;
+import com.digitalpetri.modbus.requests.WriteSingleCoilRequest;
+import com.digitalpetri.modbus.requests.WriteSingleRegisterRequest;
+import com.digitalpetri.modbus.responses.MaskWriteRegisterResponse;
+import com.digitalpetri.modbus.responses.ModbusResponse;
+import com.digitalpetri.modbus.responses.ReadCoilsResponse;
+import com.digitalpetri.modbus.responses.ReadDiscreteInputsResponse;
+import com.digitalpetri.modbus.responses.ReadHoldingRegistersResponse;
+import com.digitalpetri.modbus.responses.ReadInputRegistersResponse;
+import com.digitalpetri.modbus.responses.ReadWriteMultipleRegistersResponse;
+import com.digitalpetri.modbus.responses.WriteMultipleCoilsResponse;
+import com.digitalpetri.modbus.responses.WriteMultipleRegistersResponse;
+import com.digitalpetri.modbus.responses.WriteSingleCoilResponse;
+import com.digitalpetri.modbus.responses.WriteSingleRegisterResponse;
 import io.netty.channel.Channel;
 import io.netty.util.ReferenceCountUtil;
 
```

**Comment by mrksngl** [comment]
Thanks for sharing your project, really nice and clean :+1:

**Comment by mrksngl** [comment]
Btw: seems like I didn't have that button because I forked the repo to my organizations' account and made the PR from there.

**Comment by kevinherron** [comment]
@mrksngl I'd like ask you something unrelated to this PR:

I'm considering what will go into version 2.0 of this library. Aside from functional changes, I'm considering one of two things:
1. targeting JDK 11
2. writing in Kotlin, maintaining JDK 8 as the byte code level, and ensuring the API is 100% compatible when used from Java

Are either of those a major problem for you?

**Comment by mrksngl** [comment]
The first option: well, a lot of our projects (especially those in production) rely on java 8, at least on byte code level. Switching to Java 11 requires quite some work and I hope we'll do that some time, but just last week we agreed to stay on Java 8 a bit further.

About the second option: I have no idea about Kotlin, but generally you should have good reasons to switch the language of a whole project.

**Pull request merged**
